exports.stores = [
      {
          "id": 1,
          "area": "Adyar",
          "name": "Organic Farmer's Market",
          "address1": "38, Besant Avenue,",
          "address2": "",
          "address3": "Adyar, Chennai",
          "pincode": 600020,
          "phone": ["979 090 0887"],
          "website": "www.ofmtn.blogspot.com",
          "email": "contact@ofmtn.in"
        },
        {
          "id": 2,
          "area": "Chetpet",
          "name": "Tre Organic Farmer's Market",
          "address1": "3, Lamech Avenue, Spurtank Road",
          "address2": "Lane next to CMCT Hospital",
          "address3": "Chetpet, Chennai",
          "pincode": 600031,
          "phone": ["962 999 9019", "044 428 496 57"],
          "website": "",
          "email": "treofm@gmail.com"
        },
        {
          "id": 3,
          "area": "Medavakkam",
          "name": "Linga Bhairavi Organic Shop",
          "address1": "No. 12/29, Indira Gandhi Street",
          "address2": "Perumbakkam Main Road",
          "address3": "Medavakkam, Chennai",
          "pincode": 600100,
          "phone": ["984 087 3848"],
          "website": "",
          "email": ""
        },
        {
          "id": 4,
          "area": "Chepauk",
          "name": "Organic Farmer's Store",
          "address1": "3/5, Meeyan Sahib 2nd Street",
          "address2": "Opp Kalaivanar Arangam, Arunachalam St 1st left",
          "address3": "Chepauk, Chennai",
          "pincode": 600005,
          "phone": ["994 011 4894"],
          "website": "",
          "email": "reverse2nature@yahoo.in"
        },
        {
          "id": 5,
          "area": "R A Puram",
          "name": "Rajvilla Apartments",
          "address1": "Plot no 32, Flat no 1",
          "address2": "3rd main road",
          "address3": "R.A Puram, Chennai",
          "pincode": 600028,
          "phone": ["988 401 0355"],
          "website": "",
          "email": ""
        },
        {
          "id": 6,
          "area": "Saidapet",
          "name": "Mahatma Naturals",
          "address1": "6/122, Bazaar Road",
          "address2": "",
          "address3": "Saidapet, Chennai",
          "pincode": 600015,
          "phone": ["996 222 5225", "956 612 9298"],
          "website": "",
          "email": "consciousness09@gmail.com"
        },
        {
          "id": 7,
          "area": "Korattur",
          "name": "Prakruthi Iyarkai Angadi",
          "address1": "H - 60, Central avenue",
          "address2": "",
          "address3": "Korattur, Chennai",
          "pincode": 600080,
          "phone": ["994 095 4913"],
          "website": "",
          "email": ""
        },
        {
          "id": 8,
          "area": "Arugambakkam",
          "name": "Karima Foods (An Organic Food Store)",
          "address1": "No:499, Perumal Koil Street",
          "address2": "",
          "address3": "Arugambakkam, Chennai",
          "pincode": 600106,
          "phone": ["909 471 8909", "988 484 1764"],
          "website": "",
          "email": "karimafoods@gmail.com"
        },
        {
          "id": 9,
          "area": "K.K.Nagar",
          "name": "The Millet Store",
          "address1": "888, Munusamy Salai",
          "address2": "Next to Cake World",
          "address3": "West K.K.Nagar, Chennai",
          "pincode": 600078,
          "phone": ["984 038 3783", "994 002 9390"],
          "website": "www.themilletstore.com",
          "email": "themilletstore@gmail.com"
        },
        {
          "id": 10,
          "area": "Selaiyur",
          "name": "Sai Organics",
          "address1": "Lenin complex, Shop no. 3",
          "address2": "Bharathi School Street, Velachery Main Road",
          "address3": "Selaiyur, Chennai",
          "pincode": 600073,
          "phone": ["984 175 7916"],
          "website": "",
          "email": "saiorganicnaturals@gmail.com"
        },
        {
          "id": 11,
          "area": "Nanganallur",
          "name": "S2 Organics",
          "address1": "B 89, Hindu colony",
          "address2": "11th Cross Street",
          "address3": "Nanganallur, Chennai",
          "pincode": 600061,
          "phone": ["979 030 2828"],
          "website": "",
          "email": "s2organics@gmail.com"
        },
        {
          "id": 12,
          "area": "Perumbakkam",
          "name": "Sri Vaari Organics",
          "address1": "1201, Embassy Residency",
          "address2": "Cheran Nagar",
          "address3": "Perumbakkam, Chennai",
          "pincode": 600100,
          "phone": ["720 024 9398"],
          "website": "",
          "email": "srivaari.organics@gmail.com"
        },
        {
          "id": 13,
          "area": "Kundrathur",
          "name": "Balaji Organic Healthy Trends",
          "address1": "36, Metha Nagar Main Road",
          "address2": "Metha Nagar",
          "address3": "Kundrathur, Chennai",
          "pincode": 600069,
          "phone": ["984 012 3117"],
          "website": "",
          "email": "a.kesavan75@gmail.com"
        },
        {
          "id": 14,
          "area": "Thuraipakkam",
          "name": "Ainthinai Organic Farmers Store",
          "address1": "68, P.V.S.Nagar",
          "address2": "Near M.N.M. Jain Engineering College",
          "address3": "Thuraipakkam, Chennai",
          "pincode": 600097,
          "phone": ["994 053 7273", "909 495 5404"],
          "website": "",
          "email": "ainthinaiorganics.omr@gmail.com"
        },
    ]
